name: CI

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: yarn
      - run: yarn lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: set up node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: checkout
        uses: actions/checkout@v4
      - run: yarn
      - run: yarn test

  build-linux:
    name: Build Linux
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: set up node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: build
        run: |
          yarn
          VIV_VERSION="${{ github.ref_name }}" make linux
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vivify-linux
          path: build/linux

  build-macos:
    name: Build MacOS
    needs: [lint]
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build
        run: |
          yarn
          VIV_VERSION="${{ github.ref_name }}" make macos
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vivify-macos
          path: build/macos

  release:
    name: Release
    needs: [build-linux, build-macos]
    runs-on: ubuntu-latest
    steps:
      # release binaries -------------------------------------------------------
      - name: download linux artifact
        uses: actions/download-artifact@v4
        with:
          name: vivify-linux
          path: ./vivify-linux
      - name: download macos artifact
        uses: actions/download-artifact@v4
        with:
          name: vivify-macos
          path: ./vivify-macos
      - name: fix permissions & archive
        run: |
          chmod +x ./vivify-linux/* ./vivify-macos/*
          tar -czf vivify-linux.tar.gz vivify-linux
          tar -czf vivify-macos.tar.gz vivify-macos

      # release notes ----------------------------------------------------------
      # we check out the repo to get information from tags
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      # actions/checkout seems to have a bug where annotated tags are converted
      # to simple tags so we have to fetch them explicitly again
      # https://github.com/actions/checkout/issues/882
      - run: git fetch --tags --force origin
      - name: build release notes
        run: |
          echo -e "## What's changed\n" \
              > release.md
          git tag -l --format="%(contents)" ${{ github.ref_name }} | sed '/^-----BEGIN PGP SIGNATURE-----/,$d' \
              >> release.md
          echo -e "\n**Full changelog**: https://github.com/jannis-baum/vivify/compare/$(git tag --sort=version:refname | tail -2 | head -1)...${{ github.ref_name }}" \
              >> release.md
          echo -e '\n**SHA256 checksums**\\' \
              >> release.md
          echo -e "Linux: \`$(sha256sum vivify-linux.tar.gz | cut -d' ' -f1)\`\\" \
              >> release.md
          echo -e "macOS: \`$(sha256sum vivify-macos.tar.gz | cut -d' ' -f1)\`" \
              >> release.md
      - name: print release notes for logs
        run: cat release.md

      # release ----------------------------------------------------------------
      - name: release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          body_path: release.md
          files: vivify-*.tar.gz
