name: CI

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: set up node
        uses: actions/setup-node@v5
        with:
          node-version: 24.x
      - uses: actions/checkout@v4
      - run: yarn
      - run: yarn lint

  test:
    name: Test
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - name: set up node
        uses: actions/setup-node@v5
        with:
          node-version: 24.x
      - name: checkout
        uses: actions/checkout@v4
      - run: yarn
      - run: yarn test

  build-linux:
    name: Build Linux
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: set up node
        uses: actions/setup-node@v5
        with:
          node-version: 24.x
      - name: build
        run: |
          yarn
          VIV_VERSION="${{ github.ref_name }}" make linux
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vivify-linux
          path: build/linux

  build-macos:
    name: Build MacOS ${{ matrix.arch }}
    needs: [test]
    strategy:
      matrix:
        include:
          - os: macos-latest
            arch: arm
          - os: macos-15-intel
            arch: x86
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: 24.x
      - name: build
        run: |
          yarn
          VIV_VERSION="${{ github.ref_name }}" make macos
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: vivify-macos-${{ matrix.arch }}
          path: build/macos

  release:
    name: Release
    needs: [build-linux, build-macos]
    runs-on: ubuntu-latest
    steps:
      # we check out the repo to get information from tags
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      # release binaries -------------------------------------------------------
      - name: download linux artifact
        uses: actions/download-artifact@v4
        with:
          name: vivify-linux
          path: ./vivify-linux
      - name: download macos arm artifact
        uses: actions/download-artifact@v4
        with:
          name: vivify-macos-arm
          path: ./vivify-macos-arm
      - name: download macos x86 artifact
        uses: actions/download-artifact@v4
        with:
          name: vivify-macos-x86
          path: ./vivify-macos-x86
      - name: fix permissions & archive
        run: |
          chmod +x ./vivify-linux/* ./vivify-macos-arm/* ./vivify-macos-x86/*
          tar -czf vivify-linux.tar.gz vivify-linux
          tar -czf vivify-macos-arm.tar.gz vivify-macos-arm
          tar -czf vivify-macos-x86.tar.gz vivify-macos-x86
      # release notes ----------------------------------------------------------
      # actions/checkout seems to have a bug where annotated tags are converted
      # to simple tags so we have to fetch them explicitly again
      # https://github.com/actions/checkout/issues/882
      - run: git fetch --tags --force origin
      - name: build release notes
        run: |
          echo -e "## What's changed\n" \
              > release.md
          git tag -l --format="%(contents)" ${{ github.ref_name }} | sed '/^-----BEGIN PGP SIGNATURE-----/,$d' \
              >> release.md
          echo -e "\n**Full changelog**: https://github.com/jannis-baum/vivify/compare/$(git tag --sort=version:refname | tail -2 | head -1)...${{ github.ref_name }}" \
              >> release.md
          echo -e '\n**SHA256 checksums**\\' \
              >> release.md
          echo -e "Linux: \`$(sha256sum vivify-linux.tar.gz | cut -d' ' -f1)\`\\" \
              >> release.md
          echo -e "macOS ARM: \`$(sha256sum vivify-macos-arm.tar.gz | cut -d' ' -f1)\`\\" \
              >> release.md
          echo -e "macOS x86: \`$(sha256sum vivify-macos-x86.tar.gz | cut -d' ' -f1)\`" \
              >> release.md

      - name: print release notes for logs
        run: cat release.md

      # release ----------------------------------------------------------------
      - name: release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          body_path: release.md
          files: vivify-*.tar.gz
